### ISSUE TITLE
Questions about models and integration with 'serverless-models-plugin'

### ISSUE THREAD

**Issue by vmadman** [kennu/serverless-plugin-swagger-export#1]
I found this project during my initial research on practical Serverless implementation and was wondering if any thought about compatibility with the [serverless-models-plugin](HyperBrain/serverless-models-plugin) has went into it, or if the author is planning on implementing anything of that nature in the future.
##### Specifically:
- Has any testing went into compatibility between these two modules?
- Is it known whether or not the two plugins are mutually exclusive?
- Assuming the answers to the above questions are favorable, does the author of this plugin have any interest in extending compatibility between these two plugins?

I would not mind bringing myself and my team to the effort, but I wouldn't want to do that if we're going to be way-off-track from the plugin's core ideals and objectives.

Thanks,

**Comment by vmadman** [comment]
fyi, I asked the author of the `serverless-models-plugin` module/plugin similar questions, here:
https://github.com/HyperBrain/serverless-models-plugin/issues/4

**Comment by kennu** [comment]
Hello. I have not used serverless-models-plugin in any projects yet, so difficult to say how well it would work with serverless-plugin-swagger-export. It seems like, theoretically at least, it would be pretty easy to utilize the models definitions in `s-function.json` in generating the Swagger output.

**Comment by kennu** [comment]
I think nowadays it's best to use AWS API Gateway's built in Swagger export with Serverless 1.x, so I'm closing this. I've updated the README.
