### ISSUE TITLE
is it available a serverless v1.2.x or higher?

### ISSUE THREAD

**Issue by SteveRoland** [kennu/serverless-plugin-swagger-export#4]
Hi, kennu.

is it available a serverless v1.2.x?
I cannot find the s-project.json.

Thanks.

**Comment by kennu** [comment]
Hi, no, this only works with Serverless 0.x. I'm using AWS API Gateway's built in Swagger export for newer projects now, so I think a separate plugin is not really needed.

**Comment by SteveRoland** [comment]
Thanks, kennu.

**Comment by kennu** [comment]
I updated the README to reflect this, thanks for contributing.
