### ISSUE TITLE
Error on export

### ISSUE THREAD

**Issue by dpurrington** [kennu/serverless-plugin-swagger-export#5]
After following your instructions to install (npm install serverless-plugin-swagger-export --save and adding the plugin to my yml file) and use for export, I'm getting an error message:
TypeError: Class extends value undefined is not a function or null
    at new module.exports (/home/me/code/myproject/node_modules/serverless-plugin-swagger-export/index.js:32:56)

That is this line:
  class ServerlessPluginSwaggerExport extends S.classes.Plugin {

Is there something else I need to do to get this working?

Thanks.

**Comment by kennu** [comment]
Hi @dpurrington, I think you are using this plugin with a newer Serverless version and it no longer works, sorry about that. It was only compatible with the older 0.x versions.

**Comment by dpurrington** [comment]
No worries.  Thanks for responding!
